# Generated by Django 2.2.5 on 2019-09-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='uiid',
            new_name='uuid',
        ),
    ]
