# Generated by Django 2.2.5 on 2019-09-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190916_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='full_name',
            new_name='name',
        ),
    ]
